#ifndef EXCEPTION_H
#define EXCEPTION_H

/********************************
 * DO NOT EDIT THIS FILE
 ********************************/

class ArrayBoundsException {
	// empty class
};

class underflow {
	// empty class
};

class overflow {
	// empty class
};

class division_by_zero {
	// empty class
};

class illegal_argument {
    // empty class
};

class out_of_bounds {
	// empty class
};

#endif
